### ISSUE TITLE
How can I use jointboost on detection not classification?

### ISSUE THREAD

**Issue by samuel--hu** [yamaguchi23/jointboost#1]
Follow the readme file instruction I can use jointboost on object classification.But I don't know how to train a detector (which extract the object from background). Can you give me some advice?

**Comment by yamaguchi23** [comment]
Jointboost is just a classifier. For detection, sliding window or some object proposal methods are required.

**Comment by samuel--hu** [comment]
I don't quite understand how to use the shared features(weak classifiers?). Do I need to train the classifiers first tor get the shared feature,and then just use all the positive samples(from all class) and negative ones to train a detector?

**Comment by yamaguchi23** [comment]
I don't understand what you mean. As Jointboost is a multiclass classifier, you can train a classifier using samples of all positive classes and negative class.

**Comment by samuel--hu** [comment]
I mean in Torralba's Paper, he emphasized it's advantage in object detection. It's not merely a multiclass classify algorithm. It was designed to be used on detection. But he barely say anything about how to train the detector in his paper.
